apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n7f1dt44w-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:8c0543763002a7f4fb167b493dab46669b2bc8ee@sha256:ea4f2eefa580a883ffc8b7544a8f920e8e79f22898240df58e88d9a976ad6f64
          name: container-image
